### ISSUE TITLE
cuDNN problems?

### ISSUE THREAD

**Issue by rirri93** [soulslicer/STAF#22]
I have an error in building: 

Found cuDNN: ver. ??? found (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at cmake/Modules/FindCuDNN.cmake:43 (message):
  cuDNN version >3 is required.
Call Stack (most recent call first):
  CMakeLists.txt:427 (find_package)

### Your System Configuration

    - **CUDA version**: 10.2
    - **cuDNN version**: 8.0.5
    - **GPU model**: 2080Ti 11GB

**Comment by soulslicer** [comment]
try to compile official openpose first.

**Comment by rirri93** [comment]
I'm already using official openpose and works like a charm

**Comment by soulslicer** [comment]
Ic, it looks like the fixed Caffe to work with the 3080 cards. let me talk to the openpose author

**Comment by soulslicer** [comment]
can you try now?

**Comment by rirri93** [comment]
I've done a git pull and retried but the problem is still there

**Comment by soulslicer** [comment]
hmm..can you go run this command and tell me what you see

```
cd 3rdparty/caffe/; git branch
```

**Comment by rirri93** [comment]
No, same problem. 
I also tried to do this: https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1701
and now 

```
Building with CUDA.
CUDA detected: 10.2
Found cuDNN: ver. 8.0.5 found (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
Added CUDA NVCC flags for: sm_75
Found cuDNN: ver. ??? found (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
CMake Error at cmake/Modules/FindCuDNN.cmake:43 (message):
  cuDNN version >3 is required.
Call Stack (most recent call first):
  CMakeLists.txt:427 (find_package)
```

**Comment by soulslicer** [comment]
can you just delete everything and try again

**Comment by rirri93** [comment]
Tried. Problem's not resolved

**Comment by rirri93** [comment]
Ok problem resolved. 
In cmake/Cuda.cmake and in cmake/Modules/FindCuDNN.cmake change
`file(READ ${CUDNN_INCLUDE}/cudnn.h CUDNN_VERSION_FILE_CONTENTS`
in` file(READ ${CUDNN_INCLUDE}/cudnn_version.h CUDNN_VERSION_FILE_CONTENTS`

**Comment by rirri93** [comment]
But I have other CuDNN errors after. 
The problem is that the version of Caffe is out-of-date. 
I copied 3rdpaty/caffe from my OpenPose folder and it worked.

**Comment by senemaktas** [comment]
> Ok problem resolved.
> First in `cmake/Cuda.cmake `and in `cmake/Modules/FindCuDNN.cmake ` i changed
> `file(READ ${CUDNN_INCLUDE}/cudnn.h CUDNN_VERSION_FILE_CONTENTS`
> in` file(READ ${CUDNN_INCLUDE}/cudnn_version.h CUDNN_VERSION_FILE_CONTENTS`
> 
> but I had some other problems after, so I found another solution.
> The problem is that the version of Caffe is out-of-date.
> I copied 3rdpaty/caffe from my OpenPose folder and it worked.

hı ı have same ıssue where did you copy to caffe? thanks,,
